Tensors operations

In [3]:
import torch

# 1D Tensor
t1 = torch.tensor([1, 2, 3])
print(t1)

# 2D Tensor
t2 = torch.tensor([[1, 2], [3, 4]])
print(t2)

# Shape dekho
print(t1.shape)
print(t2.shape)

tensor([1, 2, 3])
tensor([[1, 2],
        [3, 4]])
torch.Size([3])
torch.Size([2, 2])


In [ ]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

# Addition
print(a + b)

# Multiplication
print(a * b)

# Mean
print(a.float().mean()) #pandas and  python automatically 
# float mai convert krta hai torch ko khod krwana padta hai

tensor([5, 7, 9])
tensor([ 4, 10, 18])
tensor(2.)


In [ ]:
import torch

# requires_grad=True batata hai ke
# is tensor ka gradient track karo
x = torch.tensor(3.0, requires_grad=True)

# Koi calculation karo
y = x ** 5  # y = x squared


# Gradient calculate karo
y.backward()

# Gradient dekho
print(x.grad)  # 2*x = 2*3 = 6 aana chahiye

tensor(243., grad_fn=<PowBackward0>)
tensor(405.)


In [15]:
x=torch.tensor(2.0, requires_grad=True)
y=x**9
y.backward()
print(x.grad)

tensor(2304.)


check cpu or gpu in tensor

In [19]:
print(torch.cuda.is_available())

False
