forward pass

In [17]:
import torch
import torch.nn as nn ## linear model input*weight+bias

In [18]:
model=nn.Linear(4,1) #input,output
x=torch.tensor([[0.2,5,6,5]])  #pass input tensor
output=model(x) #forward pass
print(output.item())  #single output


1.9310712814331055


In [19]:
model = nn.Linear(4, 2)  # 2 outputs
x = torch.tensor([[0.2, 5.0, 6.0, 5.0]])
output = model(x)
print(output)

tensor([[0.7444, 2.8617]], grad_fn=<AddmmBackward0>)


 Loss Calculation kya hota hai?

Definition:
Loss ek number hai jo batata hai ke model ki prediction actual answer se kitni door hai — jitna zyada loss, utna zyada model galat hai!

Example:
Socho tum ghar ki price predict kar rahi ho 🏠
ValueActual price50 lakhModel ne predict kiya43 lakhLoss7 lakh

Simple rule:

Loss zyada → model galat ❌
Loss kam → model sahi ✅
Loss zero → perfect 🎯

In [20]:
import torch
import torch.nn as nn

# Model
model = nn.Linear(2, 1)

# Input aur actual output
x = torch.tensor([[1.0, 2.0]])
actual = torch.tensor([[5.0]])  # actual answer

# Forward pass
predicted = model(x)

# Loss calculate karo
loss_fn = nn.MSELoss()
loss = loss_fn(predicted, actual)

print("Predicted:", predicted.item())
print("Loss:", loss.item())

Predicted: -0.9452197551727295
Loss: 35.34564208984375


In [24]:
model=nn.Linear(5,1)
x=torch.tensor([[1.0,2.0,3.0,4.0,5.0]])
actual=torch.tensor([[5.0]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
print(prediction.item())
print(loss.item())

0.2236841320991516
22.81319236755371


backward() kya hota hai?

Definition:
backward() woh function hai jo loss se peeche ki taraf jaata hai aur har weight ka gradient calculate karta hai — taake pata chale ke har weight ko kitna change karna hai!

Yeh 2 alag kaam hain:
FunctionKaambackward()Gradient calculate karta haioptimizer.step()Weights actually update karta hai

Simple example:
Socho tum rास्ता dhundh rahi ho 🗺️

backward() = map dekho — kidhar jaana hai
optimizer.step() = actually chalo us direction mein

In [41]:
model=nn.Linear(5,1)
x=torch.tensor([[1.0,2.0,3.0,4.0,5.0]])
actual=torch.tensor([[5.0]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
loss.backward()
for param in model.parameters():
    print(param.grad)

tensor([[-12.2782, -24.5565, -36.8347, -49.1130, -61.3913]])
tensor([-12.2782])


In [27]:
model = nn.Linear(5, 1)

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.4470,  0.2713, -0.3545, -0.1259, -0.0391]], requires_grad=True)
Parameter containing:
tensor([0.3915], requires_grad=True)


optimizer.step() kya hota hai

Definition:
optimizer.step() woh function hai jo backward() se mile gradients ko use karke weights actually update karta hai — taake agli baar model better predict kare!

Simple example:
Socho tum rasta dhundh rahi ho 🗺️

backward() = map dekha — pata chala kidhar jaana hai
optimizer.step() = actually us direction mein chali ✅


Dono mil ke kaam karte hain:
FunctionKaambackward()Gradient calculate karo — kidhar jaana haioptimizer.step()Weights update karo — actually chalo

In [65]:
import torch
import torch.nn as nn

model = nn.Linear(5, 1)
x = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0]])
actual = torch.tensor([[5.0]])

# Optimizer banao
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Forward pass
prediction = model(x)

# Loss
loss_mse = nn.MSELoss()
loss = loss_mse(prediction, actual)

# Backward
loss.backward()

# Weights update karo
optimizer.step()

print("Loss:", loss.item())

Loss: 57.25826644897461


Ab samjho kya hua:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
2 nai cheezein hain yahan: 😊

1. SGD kya hai?
SGD = Stochastic Gradient Descent
Yeh woh algorithm hai jo gradients dekh ke weights update karta hai!

2. lr=0.01 kya hai?
lr = Learning Rate
Yeh batata hai weights kitne chote chote steps mein update hon!
Learning RateMatlablr = 0.01Chhote steps ✅lr = 1.0Bohat bade steps ❌

Optimizer gradient save nahi karta — use karta hai!

Yeh karta hai:
Weight = Weight - (lr × gradient)
Weight = Weight - (0.01 × 35.0)
Weight = Weight - 0.35

In [67]:
model=nn.Linear(2,1)
x=torch.tensor([[0.1,0.5]])
actual=torch.tensor([[0.5]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
loss.backward()
optimizer.step()
print(loss)
for param in model.parameters():
    print(param.grad)


tensor(0.0197, grad_fn=<MseLossBackward0>)
tensor([[0.0280, 0.1402]])
tensor([0.2805])


Epochs vs Batches kya hota hai?

Epoch ki definition:
Epoch matlab poora dataset ek baar model se guzarna!

Simple example:
Socho tumhari 100 questions ki book hai 📚

1 Epoch = poori book ek baar parh li ✅
10 Epochs = poori book 10 baar parhi ✅


Jitne zyada epochs → model utna zyada seekhta hai! 😊


In [ ]:
import torch
import torch.nn as nn

model = nn.Linear(2, 1)
x = torch.tensor([[1.0, 2.0]])
actual = torch.tensor([[5.0]])

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_mse = nn.MSELoss()

# 10 Epochs
for epoch in range(10):
    prediction = model(x)
    loss = loss_mse(prediction, actual)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 0, Loss: 19.77781867980957
Epoch 1, Loss: 15.315943717956543
Epoch 2, Loss: 11.860666275024414
Epoch 3, Loss: 9.184901237487793
Epoch 4, Loss: 7.112786293029785
Epoch 5, Loss: 5.508141994476318
Epoch 6, Loss: 4.265505313873291
Epoch 7, Loss: 3.3032078742980957
Epoch 8, Loss: 2.5580034255981445
Epoch 9, Loss: 1.9809187650680542


In [75]:
model=nn.Linear(2,1)
x=torch.tensor([[5.0,9.0]])
actual=torch.tensor([[2.0]])
loss_mse=nn.MSELoss()

optimizer1=torch.optim.SGD(model.parameters(),lr=0.001)

for ephoc in range(10):
    
 predicted=model(x)
 loss=loss_mse(predicted,actual)
 optimizer1.zero_grad()
 loss.backward()
 optimizer1.step()
 print(f"{ephoc+1}:{loss}")
 


1:15.509607315063477
2:9.581771850585938
3:5.919580936431885
4:3.6570932865142822
5:2.2593374252319336
6:1.3958091735839844
7:0.8623253107070923
8:0.5327409505844116
9:0.3291253447532654
10:0.20333227515220642
