forward pass

In [17]:
import torch
import torch.nn as nn ## linear model input*weight+bias

In [18]:
model=nn.Linear(4,1) #input,output
x=torch.tensor([[0.2,5,6,5]])  #pass input tensor
output=model(x) #forward pass
print(output.item())  #single output


1.9310712814331055


In [19]:
model = nn.Linear(4, 2)  # 2 outputs
x = torch.tensor([[0.2, 5.0, 6.0, 5.0]])
output = model(x)
print(output)

tensor([[0.7444, 2.8617]], grad_fn=<AddmmBackward0>)


 Loss Calculation kya hota hai?

Definition:
Loss ek number hai jo batata hai ke model ki prediction actual answer se kitni door hai — jitna zyada loss, utna zyada model galat hai!

Example:
Socho tum ghar ki price predict kar rahi ho 🏠
ValueActual price50 lakhModel ne predict kiya43 lakhLoss7 lakh

Simple rule:

Loss zyada → model galat ❌
Loss kam → model sahi ✅
Loss zero → perfect 🎯

In [20]:
import torch
import torch.nn as nn

# Model
model = nn.Linear(2, 1)

# Input aur actual output
x = torch.tensor([[1.0, 2.0]])
actual = torch.tensor([[5.0]])  # actual answer

# Forward pass
predicted = model(x)

# Loss calculate karo
loss_fn = nn.MSELoss()
loss = loss_fn(predicted, actual)

print("Predicted:", predicted.item())
print("Loss:", loss.item())

Predicted: -0.9452197551727295
Loss: 35.34564208984375


In [24]:
model=nn.Linear(5,1)
x=torch.tensor([[1.0,2.0,3.0,4.0,5.0]])
actual=torch.tensor([[5.0]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
print(prediction.item())
print(loss.item())

0.2236841320991516
22.81319236755371


backward() kya hota hai?

Definition:
backward() woh function hai jo loss se peeche ki taraf jaata hai aur har weight ka gradient calculate karta hai — taake pata chale ke har weight ko kitna change karna hai!

Yeh 2 alag kaam hain:
FunctionKaambackward()Gradient calculate karta haioptimizer.step()Weights actually update karta hai

Simple example:
Socho tum rास्ता dhundh rahi ho 🗺️

backward() = map dekho — kidhar jaana hai
optimizer.step() = actually chalo us direction mein

In [41]:
model=nn.Linear(5,1)
x=torch.tensor([[1.0,2.0,3.0,4.0,5.0]])
actual=torch.tensor([[5.0]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
loss.backward()
for param in model.parameters():
    print(param.grad)

tensor([[-12.2782, -24.5565, -36.8347, -49.1130, -61.3913]])
tensor([-12.2782])


In [27]:
model = nn.Linear(5, 1)

for param in model.parameters():
    print(param)

Parameter containing:
tensor([[-0.4470,  0.2713, -0.3545, -0.1259, -0.0391]], requires_grad=True)
Parameter containing:
tensor([0.3915], requires_grad=True)


optimizer.step() kya hota hai

Definition:
optimizer.step() woh function hai jo backward() se mile gradients ko use karke weights actually update karta hai — taake agli baar model better predict kare!

Simple example:
Socho tum rasta dhundh rahi ho 🗺️

backward() = map dekha — pata chala kidhar jaana hai
optimizer.step() = actually us direction mein chali ✅


Dono mil ke kaam karte hain:
FunctionKaambackward()Gradient calculate karo — kidhar jaana haioptimizer.step()Weights update karo — actually chalo

In [65]:
import torch
import torch.nn as nn

model = nn.Linear(5, 1)
x = torch.tensor([[1.0, 2.0, 3.0, 4.0, 5.0]])
actual = torch.tensor([[5.0]])

# Optimizer banao
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

# Forward pass
prediction = model(x)

# Loss
loss_mse = nn.MSELoss()
loss = loss_mse(prediction, actual)

# Backward
loss.backward()

# Weights update karo
optimizer.step()

print("Loss:", loss.item())

Loss: 57.25826644897461


Ab samjho kya hua:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
2 nai cheezein hain yahan: 😊

1. SGD kya hai?
SGD = Stochastic Gradient Descent
Yeh woh algorithm hai jo gradients dekh ke weights update karta hai!

2. lr=0.01 kya hai?
lr = Learning Rate
Yeh batata hai weights kitne chote chote steps mein update hon!
Learning RateMatlablr = 0.01Chhote steps ✅lr = 1.0Bohat bade steps ❌

Optimizer gradient save nahi karta — use karta hai!

Yeh karta hai:
Weight = Weight - (lr × gradient)
Weight = Weight - (0.01 × 35.0)
Weight = Weight - 0.35

In [67]:
model=nn.Linear(2,1)
x=torch.tensor([[0.1,0.5]])
actual=torch.tensor([[0.5]])
prediction=model(x)
loss_mse=nn.MSELoss()
loss=loss_mse(prediction,actual)
loss.backward()
optimizer.step()
print(loss)
for param in model.parameters():
    print(param.grad)


tensor(0.0197, grad_fn=<MseLossBackward0>)
tensor([[0.0280, 0.1402]])
tensor([0.2805])


Epochs vs Batches kya hota hai?

Epoch ki definition:
Epoch matlab poora dataset ek baar model se guzarna!

Simple example:
Socho tumhari 100 questions ki book hai 📚

1 Epoch = poori book ek baar parh li ✅
10 Epochs = poori book 10 baar parhi ✅


Jitne zyada epochs → model utna zyada seekhta hai! 😊


In [ ]:
import torch
import torch.nn as nn

model = nn.Linear(2, 1)
x = torch.tensor([[1.0, 2.0]])
actual = torch.tensor([[5.0]])

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
loss_mse = nn.MSELoss()

# 10 Epochs
for epoch in range(10):
    prediction = model(x)
    loss = loss_mse(prediction, actual)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    print(f"Epoch {epoch+1}, Loss: {loss.item()}")

Epoch 0, Loss: 19.77781867980957
Epoch 1, Loss: 15.315943717956543
Epoch 2, Loss: 11.860666275024414
Epoch 3, Loss: 9.184901237487793
Epoch 4, Loss: 7.112786293029785
Epoch 5, Loss: 5.508141994476318
Epoch 6, Loss: 4.265505313873291
Epoch 7, Loss: 3.3032078742980957
Epoch 8, Loss: 2.5580034255981445
Epoch 9, Loss: 1.9809187650680542


In [75]:
model=nn.Linear(2,1)
x=torch.tensor([[5.0,9.0]])
actual=torch.tensor([[2.0]])
loss_mse=nn.MSELoss()

optimizer1=torch.optim.SGD(model.parameters(),lr=0.001)

for ephoc in range(10):
    
 predicted=model(x)
 loss=loss_mse(predicted,actual)
 optimizer1.zero_grad()
 loss.backward()
 optimizer1.step()
 print(f"{ephoc+1}:{loss}")
 


1:15.509607315063477
2:9.581771850585938
3:5.919580936431885
4:3.6570932865142822
5:2.2593374252319336
6:1.3958091735839844
7:0.8623253107070923
8:0.5327409505844116
9:0.3291253447532654
10:0.20333227515220642


In [35]:
import torch
import torch.nn as nn
data=torch.tensor([[1.0],[2.0],[3.0],[4.0],[5.0]])
output1=torch.tensor([[25000.0],[50000.0],[75000.0],[100000.0],[150000.0]])
in_norm=data/data.max()
out_norm=output1/output1.max()
model=nn.Linear(1,1)
loss_1=nn.MSELoss()
optimizer9=torch.optim.SGD(model.parameters(),lr=0.01)


In [36]:
for ephoc in range(1000):
    predicted=model(in_norm)
 
    loss=loss_1(predicted,out_norm)
    optimizer9.zero_grad()
  
    loss.backward()
    optimizer9.step()
# for param in  model.parameters():
    if ephoc%10==0:
        print(f"ephoc: {ephoc+1} and loss: {loss.item():.2f}")

ephoc: 1 and loss: 0.27
ephoc: 11 and loss: 0.17
ephoc: 21 and loss: 0.11
ephoc: 31 and loss: 0.08
ephoc: 41 and loss: 0.06
ephoc: 51 and loss: 0.04
ephoc: 61 and loss: 0.04
ephoc: 71 and loss: 0.03
ephoc: 81 and loss: 0.03
ephoc: 91 and loss: 0.03
ephoc: 101 and loss: 0.03
ephoc: 111 and loss: 0.03
ephoc: 121 and loss: 0.03
ephoc: 131 and loss: 0.03
ephoc: 141 and loss: 0.03
ephoc: 151 and loss: 0.02
ephoc: 161 and loss: 0.02
ephoc: 171 and loss: 0.02
ephoc: 181 and loss: 0.02
ephoc: 191 and loss: 0.02
ephoc: 201 and loss: 0.02
ephoc: 211 and loss: 0.02
ephoc: 221 and loss: 0.02
ephoc: 231 and loss: 0.02
ephoc: 241 and loss: 0.02
ephoc: 251 and loss: 0.02
ephoc: 261 and loss: 0.02
ephoc: 271 and loss: 0.02
ephoc: 281 and loss: 0.02
ephoc: 291 and loss: 0.02
ephoc: 301 and loss: 0.02
ephoc: 311 and loss: 0.02
ephoc: 321 and loss: 0.02
ephoc: 331 and loss: 0.02
ephoc: 341 and loss: 0.02
ephoc: 351 and loss: 0.02
ephoc: 361 and loss: 0.02
ephoc: 371 and loss: 0.02
ephoc: 381 and loss: 0.

In [39]:
new_test=torch.tensor([[10.0]])
new_9=new_test/data.max()
pre=model(new_9) * output1.max()
print(pre)


tensor([[250125.6094]], grad_fn=<MulBackward0>)


In [33]:
import torch
import torch.nn as nn

data = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
output1 = torch.tensor([[25000.0], [50000.0], [75000.0], [100000.0], [150000.0]])

# Normalize
in_norm = data / data.max()
out_norm = output1 / output1.max()

model = nn.Linear(1, 1)
loss_1 = nn.MSELoss()
optimizer9 = torch.optim.SGD(model.parameters(), lr=0.0001)

# ✅ Training Loop
for ephoc in range(2000):
    predicted = model(in_norm)        # normalized input
    loss = loss_1(predicted, out_norm) # normalized output
    optimizer9.zero_grad()
    loss.backward()
    optimizer9.step()

    if ephoc % 100 == 0:
        print(f"Epoch: {ephoc+1} | Loss: {loss.item():.6f}")

# ✅ Naya Ghar Predict Karo
new_house = torch.tensor([[6.0]])
new_norm = new_house / data.max()
predicted_price = model(new_norm) * output1.max()
print(f"\n6000 sqft ka Price: {predicted_price.item():.2f}")

Epoch: 1 | Loss: 0.263521
Epoch: 101 | Loss: 0.253422
Epoch: 201 | Loss: 0.243858
Epoch: 301 | Loss: 0.234799
Epoch: 401 | Loss: 0.226218
Epoch: 501 | Loss: 0.218090
Epoch: 601 | Loss: 0.210390
Epoch: 701 | Loss: 0.203095
Epoch: 801 | Loss: 0.196183
Epoch: 901 | Loss: 0.189634
Epoch: 1001 | Loss: 0.183429
Epoch: 1101 | Loss: 0.177548
Epoch: 1201 | Loss: 0.171975
Epoch: 1301 | Loss: 0.166692
Epoch: 1401 | Loss: 0.161685
Epoch: 1501 | Loss: 0.156938
Epoch: 1601 | Loss: 0.152438
Epoch: 1701 | Loss: 0.148171
Epoch: 1801 | Loss: 0.144124
Epoch: 1901 | Loss: 0.140287

6000 sqft ka Price: 42865.88


In [27]:
import torch
import torch.nn as nn

# Data normalize karo (0 se 1 ke beech)
data = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
output1 = torch.tensor([[25000.0], [50000.0], [75000.0], [100000.0], [150000.0]])

# ✅ Normalize
data_norm = data / data.max()          # 0.2, 0.4, 0.6, 0.8, 1.0
output_norm = output1 / output1.max() # 0.16, 0.33, 0.50, 0.66, 1.0

model = nn.Linear(1, 1)
loss_1 = nn.MSELoss()
optimizer9 = torch.optim.SGD(model.parameters(), lr=0.01)  # lr wapas 0.01

for ephoc in range(1000):
    predicted = model(data_norm)           # ✅ normalized data use karo
    loss = loss_1(predicted, output_norm)  # ✅ normalized output
    optimizer9.zero_grad()
    loss.backward()
    optimizer9.step()

    if ephoc % 100 == 0:
        print(f"Epoch: {ephoc+1} | Loss: {loss.item():.6f}")

# ✅ Prediction — wapas original scale mein
new_house = torch.tensor([[6.0]])
new_house_norm = new_house / data.max()
predicted_norm = model(new_house_norm)
predicted_price = predicted_norm * output1.max()  # original scale mein wapas
print(f"\n6000 sqft Price: {predicted_price.item():.2f}")

Epoch: 1 | Loss: 0.205489
Epoch: 101 | Loss: 0.059511
Epoch: 201 | Loss: 0.047282
Epoch: 301 | Loss: 0.037963
Epoch: 401 | Loss: 0.030572
Epoch: 501 | Loss: 0.024710
Epoch: 601 | Loss: 0.020060
Epoch: 701 | Loss: 0.016371
Epoch: 801 | Loss: 0.013445
Epoch: 901 | Loss: 0.011125

6000 sqft Price: 145114.20


In [22]:
import torch
import torch.nn as nn

# Data
data = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
output1 = torch.tensor([[25000.0], [50000.0], [75000.0], [100000.0], [150000.0]])

# Model, Loss, Optimizer — loop se BAHAR
model = nn.Linear(1, 1)
loss_1 = nn.MSELoss()
optimizer9 = torch.optim.SGD(model.parameters(), lr=0.0001)  # ✅ Small lr

# Training
for ephoc in range(1000):
    predicted = model(data)
    loss = loss_1(predicted, output1)
    optimizer9.zero_grad()
    loss.backward()
    optimizer9.step()

    if ephoc % 10 == 0:
        print(f"ephoc: {ephoc+1} and loss: {loss.item():.2f}")

# Prediction
new_house = torch.tensor([[6.0]])
print(f"\nPrice: {model(new_house).item():.2f}")

ephoc: 1 and loss: 8249585664.00
ephoc: 11 and loss: 7872549888.00
ephoc: 21 and loss: 7512959488.00
ephoc: 31 and loss: 7170007040.00
ephoc: 41 and loss: 6842924544.00
ephoc: 51 and loss: 6530974720.00
ephoc: 61 and loss: 6233459200.00
ephoc: 71 and loss: 5949710336.00
ephoc: 81 and loss: 5679089152.00
ephoc: 91 and loss: 5420989952.00
ephoc: 101 and loss: 5174832640.00
ephoc: 111 and loss: 4940065280.00
ephoc: 121 and loss: 4716158976.00
ephoc: 131 and loss: 4502612992.00
ephoc: 141 and loss: 4298947584.00
ephoc: 151 and loss: 4104704768.00
ephoc: 161 and loss: 3919448576.00
ephoc: 171 and loss: 3742764288.00
ephoc: 181 and loss: 3574254080.00
ephoc: 191 and loss: 3413540352.00
ephoc: 201 and loss: 3260261632.00
ephoc: 211 and loss: 3114073600.00
ephoc: 221 and loss: 2974649600.00
ephoc: 231 and loss: 2841676288.00
ephoc: 241 and loss: 2714854144.00
ephoc: 251 and loss: 2593898752.00
ephoc: 261 and loss: 2478539264.00
ephoc: 271 and loss: 2368516864.00
ephoc: 281 and loss: 2263583232